### ISSUE TITLE
Issue with PMD rules

### ISSUE THREAD

**Issue by humblefool-2** [buildfoundation/bazel_rules_pmd#23]
Hi,
While pulling our latest infra_versions, the bazel pinning started failing with the following error:
```
022-02-15 17:16:28,926 INFO executing "['/Users/abjain/Library/Caches/bazelisk/downloads/bazelbuild/bazel-4.2.1-darwin-x86_64/bin/bazel', 'run', '@unpinned_maven//:pin']"
ERROR: While resolving toolchains for target @bazel_tools//src/tools/launcher:launcher: invalid registered toolchain '//toolchains:all': while parsing '//toolchains:all': no such package 'toolchains': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - /Users/abjain/Desktop/Workspace/voice-triage-api/toolchains
ERROR: Analysis of target '@unpinned_maven//:pin' failed; build aborted: invalid registered toolchain '//toolchains:all': while parsing '//toolchains:all': no such package 'toolchains': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - /Users/abjain/Desktop/Workspace/voice-triage-api/toolchains
INFO: Elapsed time: 1.596s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (2 packages loaded, 6 targets configured)
FAILED: Build did NOT complete successfully (2 packages loaded, 6 targets configured)
    Fetching @local_config_sh; Restarting.
    Fetching @local_jdk; Restarting.
    Fetching @remotejdk11_linux_toolchain_config_repo; fetching
2022-02-15 17:16:30,550 INFO return code 1
```

On removing the PMD based changes, it worked fine. AFAIU, the issue is with the rule generated by PMD `//toolchains:all'` which expect it to be a package in repo and missing `@somewhere` before it. Can you please check it? It is a cool tool and we don't want to get away from using it.

**Comment by arturdryomov** [comment]
Please provide all commands and a sample (if possible) to reproduce this behavior. The current provided output is helpful but might involve a guessing game.

**Comment by humblefool-2** [comment]
I was trying to fix this by myself but when I cloned the repo and tried to build this, I'm getting the following error:
```
bazel_rules_pmd ) bazel build //...
INFO: Analyzed 9 targets (0 packages loaded, 0 targets configured).
INFO: Found 9 targets...
ERROR: /Users/abjain/Desktop/Workspace/bazel_rules_pmd/tests/analysis/BUILD:3:11: PMD tests/analysis/test_target_blank_pmd_report.txt failed: missing input file '//tests/analysis:path A.kt'
ERROR: /Users/abjain/Desktop/Workspace/bazel_rules_pmd/tests/analysis/BUILD:3:11 PMD tests/analysis/test_target_blank_pmd_report.txt failed: 4 input file(s) do not exist
INFO: Elapsed time: 0.446s, Critical Path: 0.28s
INFO: 4 processes: 4 internal.
FAILED: Build did NOT complete successfully
```

What am I missing?

**Comment by Bencodes** [comment]
@humblefool-2 Do you have a sample project that we can look at? Hard to really know what's going on without seeing your setup.

A few things that I notice right away, are you attempting to register toolchains with ":all"? Could it be sweeping up other targets that aren't meant to be registered as a toolchain?

```
invalid registered toolchain '//toolchains:all'
```

**Comment by humblefool-2** [comment]
@Bencodes I tried creating a sample project for you to reproduce it, but realised issue was due to overriding usage of `java_toolchains` in this repo and ours. Therefore, removing that dependency from ours and some other unneeded deps made it work.

Thanks for the support.
